// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg1VAehoxYC4sEAVY9QJcxdhfFT9f8uwU',
    appId: '1:21462264923:web:98c028d6083f85da0b637e',
    messagingSenderId: '21462264923',
    projectId: 'campus-micro-mobility',
    authDomain: 'campus-micro-mobility.firebaseapp.com',
    storageBucket: 'campus-micro-mobility.firebasestorage.app',
    measurementId: 'G-FVKNS5584V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvSX8lTorwDxHLEmQujtH726cYE8yiZ-M',
    appId: '1:21462264923:android:6ddff826e534c70a0b637e',
    messagingSenderId: '21462264923',
    projectId: 'campus-micro-mobility',
    storageBucket: 'campus-micro-mobility.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4BpfpafLqaGkZK0lPz8pulmpmZDJYr58',
    appId: '1:21462264923:ios:27cb8801f844d2d80b637e',
    messagingSenderId: '21462264923',
    projectId: 'campus-micro-mobility',
    storageBucket: 'campus-micro-mobility.firebasestorage.app',
    iosBundleId: 'com.example.campusMicroMbilityAndRidSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4BpfpafLqaGkZK0lPz8pulmpmZDJYr58',
    appId: '1:21462264923:ios:27cb8801f844d2d80b637e',
    messagingSenderId: '21462264923',
    projectId: 'campus-micro-mobility',
    storageBucket: 'campus-micro-mobility.firebasestorage.app',
    iosBundleId: 'com.example.campusMicroMbilityAndRidSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg1VAehoxYC4sEAVY9QJcxdhfFT9f8uwU',
    appId: '1:21462264923:web:ba5825176ab37f8f0b637e',
    messagingSenderId: '21462264923',
    projectId: 'campus-micro-mobility',
    authDomain: 'campus-micro-mobility.firebaseapp.com',
    storageBucket: 'campus-micro-mobility.firebasestorage.app',
    measurementId: 'G-66HZFYCXD1',
  );
}
